import Navbar from "@/components/ui/navigation/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BackToTop from "@/components/ui/backToTop";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Alex Farkas",
  openGraph: {
    type: "website",
    siteName: "Alex Farkas",
    title: "Alex Farkas - Web Developer",
    description:
      "A Developer who aspires to build customisable, beautiful and responsive Web Apps.",
    images: [{ url: "/assets/meta/preview.webp" }],
  },
  twitter: { card: "summary_large_image" },
  description: "Generated by create next app",
  colorScheme: "dark",
  icons: {
    icon: {
      url: "/assets/logo.svg",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Analytics />
        <SpeedInsights />
        <Navbar />
        {children}
        <BackToTop />
      </body>
    </html>
  );
}
